title: "FabAcademy 2016"
domain: https://drewrwilson.com/fabacademypodcast/
#domain: http://localhost:4000/  #uncomment for local testing only
downloadsDirectoryURL: http://yolo.dreamhosters.com/fabacademy2016-podcast/
rssURL: podcast.rss
webpageURL: https://drewrwilson.com/fabacademypodcast/
description: "FabAcademy is a five-month intensive course on digital fabrication. This is a video podcast feed of all the video lectures from the 2016 course. There are two lectures each week, one by Professor Neil Gershenfeld and also one by a guest lecturer"
language: en-US
webMaster: "literallydrew@drewrwilson.com"
image:
  url: assets/img/fabacademy-podcast-logo.jpg
  width: 1000
  height: 1000
itunes:
  author: FabAcademy 2016
  category: Technology
  category2: Non-Profit
  email: literallydrew@drewrwilson.com
  name: Drew Wilson
  explicit: clean
